DELETE http://localhost:3003/api/books/68c75b3df6c0af9a1bc6e68e
Authorization: Bearer eyJhbGclliOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFubmlrYSIsImlkIjoiNjhjNzY4Y2IyYmE1M2JmMjJkMzAwNTZhIiwiaWF0IjoxNzU3OTQyNDkwLCJleHAiOjE3NTc5NDYwOTB9.PryjvPIhlLBuDKfILuob2DSyJyRG_PIv8iTKBnIDqxU